# Ref: https://blog.blindside.io/docker-compose-go-c2bb7bed0bab#.lo5lwvpph
version: "2"

services:
  ocdweb:
    image: ocdweb:0.0.2
    volumes:
      - .:/go/src/go-with-compose
    command: go run main.go
    links:
      - mongo
    environment:
      MONGO_URL: redis:6379

  ocdservices:
    image: redis:alpine


  mongo:


  blazegraph:


  janus: